version: '2'
services:
  mtail:
    build: mtail
    command:
      - "-progs"
      - "/etc/mtail"
      - "-logs"
      - "/var/log/chia/debug.log"
      - "-logtostderr"
    volumes:
      - ${HOME}/.chia/mainnet/log/:/var/log/chia/
    network_mode: host
  # node_exporter:
  #   image: quay.io/prometheus/node-exporter:latest
  #   command:
  #     - '--path.rootfs=/host'
  #   pid: host
  #   volumes:
  #     - '/:/host:ro,rslave'
  #   network_mode: host
  chia_exporter:
    build: chia_exporter_nforks
    volumes:
      - ${HOME}/:/etc/key
    network_mode: host
  prometheus:
    build: prometheus
    volumes:
      - prom_data:/prometheus
    network_mode: host
  loki:
    image: grafana/loki:2.0.0
    command: -config.file=/etc/loki/local-config.yaml
    network_mode: host
  promtail:
    build: promtail
    volumes:
      - ${HOME}/.chia/mainnet/log:/var/log/chia
      - ${HOME}/.chia/mainnet/plotter:/var/log/plotter
    command: -config.file=/etc/promtail/config.yml
    network_mode: host
  grafana:
    build: grafana
    network_mode: host
volumes:
  prom_data:
